### ISSUE TITLE
Nonces for the CSS of inlined SVGs (with Craft’s svg function)

### ISSUE THREAD

**Issue by mprofitlich** [born05/craft-csp#10]
Inlined SVGs have a `<style>` tag. With CSP it is ignored, as it should. Thus using Craft’s `{{ svg }}` function leads to unstyled SVGs.

I suggest to add a functionality to this plugin that inserts a nonce to inlined SVGs. An example:

```
<svg id="zboywbwdqa-a" viewBox="0 0 164 164">
  <defs>
    <style nonce="b4c66027a2409b92fc0b33ac1b29ae77a56f3ecc899e">
      .zboywbwdqa-i {
        fill: #fff;
      }
    </style>
  </defs>
  <circle class="zbokwbwcqa-i" cx="82" cy="82" r="82"></circle>
</svg>
```

**Comment by roelvanhintum** [comment]
Sorry, completely missed this. For future reference, this could be solved with: `nonce="{{ cspNonce('style-src') }}"`
See README.md for more info and examples
