### ISSUE TITLE
{% css %} twig tags are working! :D

### ISSUE THREAD

**Issue by peteralewis** [born05/craft-csp#2]
Me Again!

Readme documentation states:

> Currently does not work in combination with {% js %} or {% css %} twig tags.

It does work:

```
    {% set inlineCSS %}
        .myStyleClass { fill: black; }
    {% endset %}
    {% css inlineCSS with {nonce: cspNonce('style-src')} %}
```

Ref: https://docs.craftcms.com/v3/dev/tags.html#css

{% js %} doesn't support `with`, so won't work, but easy enough to use:

```
{% minify %}
    <script nonce="{{ cspNonce('script-src') }}">
        ...
    </script>
{% endminify %}
```

**Comment by roelvanhintum** [comment]
@peteralewis thanks! Just added it to the docs.
