### ISSUE TITLE
Unable to use Craft Debug Toolbar

### ISSUE THREAD

**Issue by peteralewis** [born05/craft-csp#4]
Sorry, going to have to re-open this one.

I believe Craft v3.5.0 changed something regarding this setting and it appears to no longer be stored in the session:
"Deprecated craft\web\User::destroyDebugPreferencesInSession()."
"Deprecated craft\web\User::saveDebugPreferencesToSession()."

The addition you made to Plugin.php (line 61) to fix this I had to change to:
if ( Craft::$app->users->getUserPreference(Craft::$app->user->id,'enableDebugToolbarForSite') ) return;

Couldn't work out how to do it using the user class - it's documented that getPreference() is available, but doesn't work. So hence having to use users class.

**Comment by roelvanhintum** [comment]
Thanks @peteralewis! The `getPreference` method was available on the User element instead of the session User.

**Comment by roelvanhintum** [comment]
Released in 1.2.1
